### Import the necessary libraries

In [209]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set()

### Load my csv file

#### Explore the data

In [210]:
raw_data = pd.read_csv('./energydata_complete.csv')
raw_data.describe(include='all')

date    Appliances        lights            T1  \
count                 19735  19735.000000  19735.000000  19735.000000   
unique                19735           NaN           NaN           NaN   
top     2016-02-07 14:50:00           NaN           NaN           NaN   
freq                      1           NaN           NaN           NaN   
mean                    NaN     97.694958      3.801875     21.686571   
std                     NaN    102.524891      7.935988      1.606066   
min                     NaN     10.000000      0.000000     16.790000   
25%                     NaN     50.000000      0.000000     20.760000   
50%                     NaN     60.000000      0.000000     21.600000   
75%                     NaN    100.000000      0.000000     22.600000   
max                     NaN   1080.000000     70.000000     26.260000   

                RH_1            T2          RH_2            T3          RH_3  \
count   19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
unique           NaN           NaN           NaN           NaN           NaN   
top              NaN           NaN           NaN           NaN           NaN   
freq             NaN           NaN           NaN           NaN           NaN   
mean       40.259739     20.341219     40.420420     22.267611     39.242500   
std         3.979299      2.192974      4.069813      2.006111      3.254576   
min        27.023333     16.100000     20.463333     17.200000     28.766667   
25%        37.333333     18.790000     37.900000     20.790000     36.900000   
50%        39.656667     20.000000     40.500000     22.100000     38.530000   
75%        43.066667     21.500000     43.260000     23.290000     41.760000   
max        63.360000     29.856667     56.026667     29.236000     50.163333   

                  T4  ...            T9          RH_9         T_out  \
count   19735.000000  ...  19735.000000  19735.000000  19735.000000   
unique           NaN  ...           NaN           NaN           NaN   
top              NaN  ...           NaN           NaN           NaN   
freq             NaN  ...           NaN           NaN           NaN   
mean       20.855335  ...     19.485828     41.552401      7.411665   
std         2.042884  ...      2.014712      4.151497      5.317409   
min        15.100000  ...     14.890000     29.166667     -5.000000   
25%        19.530000  ...     18.000000     38.500000      3.666667   
50%        20.666667  ...     19.390000     40.900000      6.916667   
75%        22.100000  ...     20.600000     44.338095     10.408333   
max        26.200000  ...     24.500000     53.326667     26.100000   

         Press_mm_hg        RH_out     Windspeed    Visibility     Tdewpoint  \
count   19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
unique           NaN           NaN           NaN           NaN           NaN   
top              NaN           NaN           NaN           NaN           NaN   
freq             NaN           NaN           NaN           NaN           NaN   
mean      755.522602     79.750418      4.039752     38.330834      3.760707   
std         7.399441     14.901088      2.451221     11.794719      4.194648   
min       729.300000     24.000000      0.000000      1.000000     -6.600000   
25%       750.933333     70.333333      2.000000     29.000000      0.900000   
50%       756.100000     83.666667      3.666667     40.000000      3.433333   
75%       760.933333     91.666667      5.500000     40.000000      6.566667   
max       772.300000    100.000000     14.000000     66.000000     15.500000   

                 rv1           rv2  
count   19735.000000  19735.000000  
unique           NaN           NaN  
top              NaN           NaN  
freq             NaN           NaN  
mean       24.988033     24.988033  
std        14.496634     14.496634  
min         0.005322      0.005322  
25%        12.497889     12.497889  
50%        24.897653     24.897653  
7

### Drop the columns that are not 

In [211]:
data = raw_data.drop(['date', 'lights'], axis=1)

In [212]:
data.head()

Appliances     T1       RH_1    T2       RH_2     T3       RH_3         T4  \
0          60  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000   
1          60  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000   
2          50  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667   
3          50  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000   
4          60  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000   

        RH_4         T5  ...         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  45.566667  17.166667  ...  17.033333  45.53  6.600000        733.5    92.0   
1  45.992500  17.166667  ...  17.066667  45.56  6.483333        733.6    92.0   
2  45.890000  17.166667  ...  17.000000  45.50  6.366667        733.7    92.0   
3  45.723333  17.166667  ...  17.000000  45.40  6.250000        733.8    92.0   
4  45.530000  17.200000  ...  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410389  45.410389  
4   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 27 columns]

In [213]:
data.describe(include='all')

Appliances            T1          RH_1            T2          RH_2  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      97.694958     21.686571     40.259739     20.341219     40.420420   
std      102.524891      1.606066      3.979299      2.192974      4.069813   
min       10.000000     16.790000     27.023333     16.100000     20.463333   
25%       50.000000     20.760000     37.333333     18.790000     37.900000   
50%       60.000000     21.600000     39.656667     20.000000     40.500000   
75%      100.000000     22.600000     43.066667     21.500000     43.260000   
max     1080.000000     26.260000     63.360000     29.856667     56.026667   

                 T3          RH_3            T4          RH_4            T5  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      22.267611     39.242500     20.855335     39.026904     19.592106   
std        2.006111      3.254576      2.042884      4.341321      1.844623   
min       17.200000     28.766667     15.100000     27.660000     15.330000   
25%       20.790000     36.900000     19.530000     35.530000     18.277500   
50%       22.100000     38.530000     20.666667     38.400000     19.390000   
75%       23.290000     41.760000     22.100000     42.156667     20.619643   
max       29.236000     50.163333     26.200000     51.090000     25.795000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 27 columns]

### Standardize the data and Create Linear regression model
#### Declare the input and targets
#### Scale the data

In [214]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
normalised_data = pd.DataFrame(scaler.fit_transform(data), columns=data.columns)
features_data = normalised_data.drop(columns=['Appliances'], axis=1)
appliances_target = normalised_data['Appliances']

### Train Test Split

In [215]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(features_data,appliances_target, test_size = 0.3, random_state = 42)
reg = LinearRegression()
reg.fit(x_train,y_train)
predicted_values = reg.predict(x_test)

In [216]:
predicted_values

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

### Mean Absolute Erroe

In [217]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 3)

0.05

### R-Squared

In [218]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_values)
round(r2_score, 3)

0.149

### Residual Sum of Squares

In [219]:
rss = np.sum(np.square(y_test - predicted_values))
round(rss, 3)

45.348

### Root Mean Squared Error

In [233]:
from sklearn.metrics import  mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)

0.088

In [221]:
y_hat = reg.predict(x_train)
y_hat

array([0.03736239, 0.08440778, 0.02815806, ..., 0.04623579, 0.08713294,
       0.07302946])

### Finding the weights and bias

#### Coefficient

In [232]:
weights = reg.coef_
weights = ['{:f}'.format(x) for x in weights]

#### Intercept

In [223]:
bias = reg.intercept_
bias.round(3)

0.153

In [225]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha= 0.4)
ridge_reg.fit(x_train, y_train)

ridge_predicted_values = ridge_reg.predict(x_test)
ridge_predicted_values

array([0.03321872, 0.24043824, 0.03461337, ..., 0.06872351, 0.10025536,
       0.05851175])

### Lasso Regression

In [226]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.001)

### RMSE of Lasso Regression

In [231]:
lasso_predicted_values = lasso_reg.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, lasso_predicted_values))
round(rmse, 3)

0.094

### Ridge Regression

In [229]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.5)
ridge_reg.fit(x_train, y_train)

Ridge(alpha=0.5)

### RMSE of Ridge Regression

In [230]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, ridge_predicted_values))
round(rmse, 3)

0.088

In [227]:
reg_summary = pd.DataFrame(features_data.columns.values, columns=['Features'])
reg_summary['Weight'] = weights

ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

final_weights = pd.merge(reg_summary, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')

final_weights

Features     Weight  Ridge_Weight  Lasso_weight
0            T1  -0.003281     -0.018406      0.000000
1          RH_1   0.553547      0.519525      0.017880
2            T2  -0.236178     -0.201397      0.000000
3          RH_2  -0.456698     -0.411071     -0.000000
4            T3   0.290627      0.288087      0.000000
5          RH_3   0.096048      0.095135      0.000000
6            T4   0.028981      0.027384     -0.000000
7          RH_4   0.026386      0.024579      0.000000
8            T5  -0.015657     -0.019853     -0.000000
9          RH_5   0.016006      0.016152      0.000000
10           T6   0.236425      0.217292      0.000000
11         RH_6   0.038049      0.035519     -0.000000
12           T7   0.010319      0.010098     -0.000000
13         RH_7  -0.044614     -0.045977     -0.000000
14           T8   0.101995      0.101028      0.000000
15         RH_8  -0.157595     -0.156830     -0.000110
16           T9  -0.189941     -0.188916     -0.000000
17         RH_9  -0.039800     -0.041367     -0.000000
18        T_out  -0.321860     -0.262172      0.000000
19  Press_mm_hg   0.006839      0.006584     -0.000000
20       RH_out  -0.077671     -0.054724     -0.049557
21    Windspeed   0.029183      0.030268      0.002912
22   Visibility   0.012307      0.012076      0.000000
23    Tdewpoint   0.117758      0.083128      0.000000
24          rv1   0.000770      0.000748     -0.000000
25          rv2   0.000770      0.000748     -0.000000